name: Build binaries and create releases

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.20.2
            - name: Build binaries
              run: |
                  export VERSION=$(grep -o -E '([0-9]+\.){2}[0-9]+' main.go)

                  echo "Building for macOS"
                  GOOS=darwin GOARCH=amd64 go build -o dist/darwin-amd64/str
                  zip -j dist/darwin-amd64.zip dist/darwin-amd64/**

                  echo "Building for Linux"
                  GOOS=linux GOARCH=amd64 go build -o dist/linux-amd64/str
                  zip -j dist/linux-amd64.zip dist/linux-amd64/**

                  echo "Building for Windows"
                  GOOS=windows GOARCH=amd64 go build -o dist/windows-amd64/str.exe
                  zip -j dist/windows-amd64.zip dist/windows-amd64/**
            - name: Create release and tag
              uses: softprops/action-gh-release@v1
              with:
                  files:
                      - dist/*.zip
                  tag_name: ${{ env.VERSION }}
                  name: Release ${{ env.VERSION }}
                  body: Auto-generated release for version ${{ env.VERSION }}
                  draft: false
                  prerelease: false
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
