name: Build binaries and create releases

on:
    push:
        tags:
            - '*'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Set up Go
              uses: actions/setup-go@v2
              with:
                  go-version: 1.20.2
            - name: Build binaries
              run: ./build.sh
            - name: Create release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref }}
                  release_name: Release ${{ github.ref }}
                  body: |
                      Changes in this Release:
                      $(git log --pretty=format:"%h %s (%an)" ${GITHUB_REF#refs/*/HEAD}..HEAD)
                  draft: false
                  prerelease: false
            - name: Upload binaries
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: |
                      dist/linux-amd64.zip
                      dist/darwin-amd64
                      dist/windows-amd64.zip
                  asset_name: |
                      linux-amd64.zip
                      darwin-amd64.zip
                      windows-amd64.zip
                  asset_content_type: application/octet-stream
